/**
* wrapper class used in creating external Lead.
*
* @author Dayakar Deekonda 
*
* @date JAN 23th 2023
* 
*/
public class AOB_API_BusinnessLeadWrapper {
    public String type;
	public String source;
	public String description;
	public String leadId;
	public String appName;
	public String surname;
	public String businessType;
	public String businessName;
	public String email;
	public String businessRegNumber;
	public String idNumber;
	public String submittedDate;
	public String contactNumber;
	public String altContactNumber;
	public String priority;
	public String applicationGuid;
	public String sbsaCustomer;
	public String popiConsent;
	public String province;
	public String city;
	public String externalApplicationId;
	public String reason;

}