/**
* @description       : Constant class staff assisted work.
* @author            : Tukelo Moseamo
* @group             : StandardBank BCC
* @last modified on  : 02-12-2024
* @last modified by  : Tukelo Moseamo
* Modifications Log
* Ver   Date         Author           Modification Description: SFP-25088 
* 1.0   05-19-2023   Tukelo Moseamo   Initial Version
**/
public class AOB_Internal_Constants {
    
    //Tukelo : Fields used for staff Assist Contract workflow
    public static final String ITEM_ID = 'itemId';
    public static final String DOCUMENT_NAME = 'documentName';
    public static final String NO_CONTRACTS = 'No documents where found for processing at the moment.'; 
    public static final String WORKFLOW_MODE = 'ONLY_OTHERS';
    public static final String NO_RECORD_FOUND = 'No Record found for the provided Id: ';
    public static final String PRE_APPLICATION_RESPONSE = 'preApplicationResponse'; 
    public static final String CIPC_REGISTERED_DETAILS = 'cipcRegisteredDetails'; 
    public static final String BUSINESS_DETAILS = 'businessDetails';
    public static final String BUSINESS_FLAG = 'P';
    public static final String DOCUMENT_ID = '0';
    public static final String NOTIFICATIONS = 'Notifications';
    public static final String CARD_SELECTION = 'Card Selection';
    public static final String NO_NODE_FOUND_MESSAGE = ' Node could not be found';
    public static final String NOTIFIEDMEAN = 'NotifiedMean';
    public static final String DELIVERY_METHOD = 'Delivery method';
    public static final String DELIVERY_ADDRESS = 'Deliver Address';
    public static final String BUSINESS_MARKETLINK_PRODUCTCODE = '4488';
    public static final String UUID = 'uuid';
    public static final String CUSTOMER = 'customer';
    public static final String FALSE_VALUE = 'false';
    public static final String TRUE_VALUE = 'true';
    public static final String MARKETING_CONSENT = 'Marketing Consent Internal';

    public static final String COMPANYDETAILRAN = 'Company Detail Ran';
    public static final String APPLICATION_PROCESS_DATA_RESPONSE = 'getApplicationProcessDataResponse';
    public static final String SOLE_PROPRIETORSHIP = 'SOLE PROPRIETORSHIP';
    public static final String CLOSE_CORPORATION = 'CLOSE CORPORATION';
    public static final String PRIVATE_COMPANY = 'PRIVATE COMPANY';
    public static final String PROCESS_APPLICATION_DATA_EMPTY = 'Process Application Data not found. Please contact your System Administrator';
    public static final String PROCESS_APPLICATION_DIRECTOR_EMPTY = 'No directors found for this client. Please contact your System Administrator';
    public static final String SUCCESSFUL = 'SUCCESSFUL';
    public static final String SUCCESS = 'SUCCESS';
    public static final String SUCCESSFUL_CODE = '200';
    public static final String CONTRACT_DOCUMENT = 'ContractDocument';
    public static final String CREATE_CONTRACT_RESPONSE = 'createContractResponse';
    public static final String EXECUTE_ACCOUNT = 'executeAccountOnboardingResponse';

    public static final String POCKETBIZ_CODE = 'ZPOB';
    public static final String CONTRACTS_EXISTS = 'Contracts have already been generated';
    public static final String INFO = 'INFO';
    public static final String ERROR = 'ERROR';
    public static final String WARNING = 'WARNING';
    public static final String  WORKFLOW_TYPE = 'SERIAL';

    public static final String PASSWORD = 'password';
    public static final String USERNAME = 'username';
    public static final String SCOPE = 'scope';
    public static final String SIGNING_HUB_CHANNEL_ID = 'SALESFORCE_STAFF_ASSISTED';
    public static final String SIGNER = 'SIGNER';
    public static final String REVIEWER = 'REVIEWER';
    public static final String PACKAGE_NAME = 'Application for business current account';
    public static final String ELECTRONIC_SIGNATURE = 'electronic_signature';
    
    public static final String STAFF_ASSIST = 'Staff Assisted';
    public static final String STAFF_AND_STAFF = 'Self & Staff';
    public static final String NO_APPLICATION = 'Application not found';
    public static final String SELF_ASSIST = 'Self Assisted';

    public static final String SIGNATORY_ROLE = 'Z0000086';
    public static final String AUTHORISED_CARD_USER_ROLE = 'Z0000088';
public static final String RESERVE_BANK_CODE = 'resBank';
	public static final String FORM_FIFTY = 'Form50';
	public static final String CONSENT_STATUS = 'consentStatus';
	public static final String CONSENT_CODE = 'consentCode';
	public static final String BUSINESS_REG_NO = 'businessRegistrationNumber';
	public static final String DEFAULTED_MARKETING_CONSENT = 'DefaultedMarketingConsents';
	public static final String CONSENT_FOR_EMAIL = 'consentForEmail';
	public static final String CONSENT_FOR_SMS ='consentForSMS';
	public static final String CONSENT_FOR_TELESALES = 'consentForTelleSales';
	public static final String CONSENT_FOR_MARKETING_RESEARCH = 'consentForMarketingResearch';
	public static final String CONSENT_FOR_MARKETING = 'consentForRecieveMarketing';
	public static final String CONSENT_FOR_ATTESTATION = 'consentForStaffAttestation';
	public static final String MARKETING_CONSENTS = 'marketingConsents';
	public static final String ADDRESS_TYPE = 'AddressType';
	public static final String MORE_LESS_CLASSIFICATION = 'MoreLessClassif';
	public static final String FOREIGN_TAX_RESIDENCY = 'FOREIGN TAX RESIDENCY';
	public static final String BUSINESS_FUNDING = 'BUSINESS FUNDING';
	public static final String ENTITY_CLASSIFICATION = 'ENTITY CLASSIFICATION';
	public static final String COMPANY_FINANCIAL_DETAIL = 'Company Financial Details';
}