/**
* Class used to Perform an API call to persist user info in SAP
*
* @author Dayakar Deekonda
*
* @date Nov 23th 2022
* 
* ACTION  TICKET    DATE       OWNER         COMMENT
* Changed          21-01-2023  Gill Lumley   Removed commented code, debug statements and white space 
*/

public class AOB_GetAccessToken {
    
    public String access_token;	
	public String refresh_token;	
	public String id_token;	
	public String token_type;	
	public Integer expires_in;

}