/***************************************************************************************
* @Name of the Class     :ZAF_CTRL_ClientPricingLetterConstants
* @description           :Class for Global variable and constant names for zafin client pricing letter
* @Author                :Pradeep Kota  
* @Created Date          :Sep 27th 2023
/***************************************************************************************
*@Last Modified By  : Pradeep Kota  
*@Last Modified On  : 11 Mar 2024
*@Modification Description : SFP-30098
***************************************************************************************/
public class ZAF_CTRL_ClientPricingLetterConstants {
    	public static final String ZAFIN_FEE_CURRENT_ACCOUNT = 'Current Account';
    	public static final String ZAFIN_PRICING_CONTACT = 'Pricing Contact';
		public static final String ZAFIN_GROUP_PRICING_CONTACT = 'Group Pricing Contact';
    	public static final String ZAFIN_PRICING_AND_BILLING ='Pricing and Billing';
    	public static final String ZAFIN_MONTHLY_ENVIRONMENT_LETTER ='ZAF Monthly Environmental Letter';
    	public static final String ZAFIN_CORPORATE_LETTER ='ZAF Corporate Annual Pricing Letter';
    	public static final String ZAFIN_2023_ANNUAL_PRICE_REVIEW ='2024 Price Review | ';
    	public static final String ZAFIN_NO_ASSOCIATED_CONTACT_EMAIL='There is no contact with contact role as pricing contact, please enter the email address manually to send the email';
        public static final String ZAFIN_CORPORATE='Corporate';
        public static final String ZAFIN_CORPORATE_ANNUAL_LETTER='Corporate Annual Letter';
        public static final String ZAFIN_BANK_SECTOR_LETTER='Bank sector Letter';
        public static final String ZAF_BANK_SECTOR='ZAF Bank Sector';
        public static final String ZAF_STANDARD_PRICING ='Standard Pricing.pdf';
    

}